# Ejemplo de configuración base que estaría en config repo
# Ruta: kubernetes-ejercicios-config/base/backend/deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: PROJECT/BACKEND
          ports:
            - containerPort: 3000
          env:
            - name: POSTGRES_HOST
              value: "postgres-svc"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: password
            - name: POSTGRES_DB
              value: "todos"
            - name: PORT
              value: "3000"
            - name: NATS_URL
              value: "nats://nats-server:4222"
            - name: ENVIRONMENT
              value: "unknown"
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
