apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      containers:
        - name: log-output
          image: PROJECT/LOG_OUTPUT
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: log-output
spec:
  selector:
    app: log-output
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
