apiVersion: batch/v1
kind: CronJob
metadata:
  name: wiki-todo-generator-test
  namespace: project
spec:
  # Ejecutar cada minuto para testing
  schedule: "*/1 * * * *"
  
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  
  jobTemplate:
    spec:
      activeDeadlineSeconds: 300
      
      template:
        spec:
          restartPolicy: Never
          
          containers:
          - name: wiki-todo
            image: wiki-todo-app:latest
            imagePullPolicy: Never
            
            env:
            - name: BACKEND_URL
              value: "http://todo-backend-db-svc:3000"
            
            resources:
              requests:
                cpu: 100m
                memory: 64Mi
              limits:
                cpu: 500m
                memory: 256Mi
