apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - backend/kustomization.yaml
  - postgres/kustomization.yaml
  - ping-pong/kustomization.yaml
  - log-output/kustomization.yaml
  - broadcaster/kustomization.yaml

namespace: default

commonLabels:
  project: the-project
