apiVersion: v1
kind: Service
metadata:
  namespace: project
  name: project-svc
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    app: project
