apiVersion: apps/v1
kind: Deployment
metadata:
  name: broadcaster-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broadcaster
  template:
    metadata:
      labels:
        app: broadcaster
    spec:
      containers:
        - name: broadcaster
          image: mluukkai/dwk-app6-broadcaster:stable
          ports:
            - containerPort: 3002
          env:
            - name: NATS_URL
              value: "nats://nats-server:4222"
            - name: DISCORD_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: external-services
                  key: discord_url
                  optional: true
            - name: TELEGRAM_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: external-services
                  key: telegram_token
                  optional: true
            - name: SLACK_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: external-services
                  key: slack_url
                  optional: true
            - name: LOG_ONLY
              value: "false"
          livenessProbe:
            httpGet:
              path: /health
              port: 3002
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 3002
            initialDelaySeconds: 5
            periodSeconds: 5
