apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

images:
  - name: PROJECT/BACKEND
    newName: mluukkai/dwk-app6-api
    newTag: stable
