apiVersion: apps/v1
kind: Deployment
metadata:
  name: random-logger-declarative
spec:
  replicas: 1
  selector:
    matchLabels:
      app: random-logger-declarative
  template:
    metadata:
      labels:
        app: random-logger-declarative
    spec:
      containers:
      - name: random-logger
        image: merkuryom/random-logger:v1