apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: project
data:
  DB_HOST: "postgres-stset-0.postgres-svc"
  DB_PORT: "5432"
  DB_NAME: "pingpong"
  DB_USER: "pingpong"
  DB_PASSWORD: "pingpong123"
